### ISSUE TITLE
Http server acccess outside of localhost

### ISSUE THREAD

**Issue by Themis3000** [Skiouros/AHKhttp#8]
I'm having troubles accessing the http server on another device on the same network. Using http://10.0.0.31:8000/ (my local ip address) on my local machine works, but it doesn't work on other devices on the same network. How do I ensure the service is exposed to all ip addresses and not just localhost?

**Comment by rtayne** [comment]
Make sure in your Windows Firewall settings you have enabled World Wide Web Services (HTTP).

**Comment by Themis3000** [comment]
@rtayne 

That seemed to be the issue, thank you! I seem to forget about windows firewall every time I run into something like this 🤦‍♀️
